# ===========================================================================
# Project:   SCXIB
# Copyright: ©2010 Robert Linton
# Contributors: Devin Torres, Kurt Williams
# ===========================================================================

config :demo_app, :required => :scxib
